### ISSUE TITLE
[Suggestion] Pagination

### ISSUE THREAD

**Issue by Chinay-Domitrix** [PlayPro/CoreProtect#521]
Add a config option to set custom item counts for pagination or to outright disable pagination (for the brave-hearted)

Example config snippet:
```yml
- pagination:
    enabled: true
    itemCount: 20
```
